name: RapidAPI latency US

on: workflow_dispatch   # 수동 실행

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Curl test
        env:
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        run: |
          URL='https://instagram-social-api.p.rapidapi.com/v1/search_posts?search_query=%EB%A6%BD%EB%B0%A4'
          curl -s -D - \
               -H "x-rapidapi-host: instagram-social-api.p.rapidapi.com" \
               -H "x-rapidapi-key: $RAPIDAPI_KEY" \
               -w '\n---- timing ----\nhttp=%{http_code} dns=%{time_namelookup}s connect=%{time_connect}s ttfb=%{time_starttransfer}s total=%{time_total}s\n' \
               "$URL" | head -n 40
