name: RapidAPI latency US

on: workflow_dispatch   # 수동 실행

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Curl test
        env:
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        run: |
          URL='https://instagram-social-api.p.rapidapi.com/v1/search_posts?search_query=%EB%A6%BD%EB%B0%A4'
          for i in {1..5}; do
            curl -s -o /dev/null \
                 -H "x-rapidapi-host: instagram-social-api.p.rapidapi.com" \
                 -H "x-rapidapi-key: $RAPIDAPI_KEY" \
                 -w 'run='$i' total=%{time_total}s\n' \
                 "$URL"
          done
